version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"
    target-branch: "2-frontend"
    open-pull-requests-limit: 20
    labels:
      - "ğŸ“¦dependencies"
      - "ğŸ› ï¸npm"
      - "ğŸ¤–Dependabot"
    assignees:
      - "An0n-00"
    commit-message:
      prefix: "[dependabot - npm] "
      
  - package-ecosystem: "nuget" 
    directory: "/src/backend" 
    schedule:
      interval: "weekly"
    target-branch: "3-implement-all-controllers"
    open-pull-requests-limit: 20
    labels:
      - "ğŸ“¦dependencies"
      - "ğŸ’»csharp"
      - "ğŸ¤–Dependabot"
    assignees:
      - "An0n-00"
    commit-message:
      prefix: "[dependabot - csharp] "
