version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "ğŸ“¦dependencies"
      - "ğŸ› ï¸npm"
    assignees:
      - "An0n-00"
    commit-message:
      prefix: "[dependabot - npm] "
      
  - package-ecosystem: "nuget" 
    directory: "/src/backend" 
    schedule:
      interval: "weekly"
    labels:
      - "ğŸ“¦dependencies"
      - "ğŸ’» csharp"
    assignees:
      - "An0n-00"
    commit-message:
      prefix: "[dependabot - csharp] "
