name: Frontend CD

on:
  push:
    branches: [2-frontend]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install --force
        working-directory: ./src/frontend

      - name: Build project
        run: npm run build --if-present
        working-directory: ./src/frontend

      - name: Fix hard coded linking to relative paths
        run: |
          sed -i 's/\/assets/\.\/assets/g' ./dist/index.html
          sed -i 's/\/IT-Ticket\/assets/\.\/assets/g' ./dist/index.html
        working-directory: ./src/frontend

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/frontend/dist
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          keep_files: false
          commit_message: "Deploy to GitHub Pages"
